using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class ActivationStatus
	{


		[DataMember(Name = "user_id", IsRequired=false)]
		public int? UserId { get; set; }


		[DataMember(Name = "status", IsRequired=false)]
		public string Status { get; set; }


		[DataMember(Name = "mail", IsRequired=false)]
		public string Mail { get; set; }


		[DataMember(Name = "space_count", IsRequired=false)]
		public int? SpaceCount { get; set; }


	}
}

