using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class ContractUser : User
	{


		[DataMember(Name = "subtotal", IsRequired=false)]
		public float Subtotal { get; set; }


		[DataMember(Name = "items", IsRequired=false)]
		public Dictionary<string,object> Items { get; set; }


	}
}

