using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class ContractPrice
	{


		[DataMember(Name = "total", IsRequired=false)]
		public float Total { get; set; }


		[DataMember(Name = "sub_total", IsRequired=false)]
		public float SubTotal { get; set; }


		[DataMember(Name = "quantity", IsRequired=false)]
		public int? Quantity { get; set; }


		[DataMember(Name = "already_paid", IsRequired=false)]
		public int? AlreadyPaid { get; set; }


		[DataMember(Name = "users", IsRequired=false)]
		public List<ContractUser> Users { get; set; }


	}
}

