using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class ContractPriceV2
	{


		[DataMember(Name = "price", IsRequired=false)]
		public float Price { get; set; }


		[DataMember(Name = "quantity", IsRequired=false)]
		public int? Quantity { get; set; }


	}
}

