using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class LinkedAccount
	{


		[DataMember(Name = "linked_account_id", IsRequired=false)]
		public int? LinkedAccountId { get; set; }


		[DataMember(Name = "label", IsRequired=false)]
		public string Label { get; set; }


		[DataMember(Name = "provider", IsRequired=false)]
		public string Provider { get; set; }


		[DataMember(Name = "provider_humanized_name", IsRequired=false)]
		public string ProviderHumanizedName { get; set; }


		[DataMember(Name = "capability_names", IsRequired=false)]
		public Dictionary<string,object> CapabilityNames { get; set; }


		[DataMember(Name = "options", IsRequired=false)]
		public Dictionary<string,object> Options { get; set; }


	}
}

