using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class NotificationGroup
	{


		[DataMember(Name = "context", IsRequired=false)]
		public Dictionary<string,object> Context { get; set; }


		[DataMember(Name = "notifications", IsRequired=false)]
		public Dictionary<string,object> Notifications { get; set; }


	}
}

