using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class QuestionOption
	{


		[DataMember(Name = "question_option_id", IsRequired=false)]
		public int? QuestionOptionId { get; set; }


		[DataMember(Name = "text", IsRequired=false)]
		public string Text { get; set; }


	}
}

