using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class Referral
	{


		[DataMember(Name = "code", IsRequired=false)]
		public string Code { get; set; }


		[DataMember(Name = "status", IsRequired=false)]
		public string Status { get; set; }


	}
}

