using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class Subscription
	{


		[DataMember(Name = "started_on", IsRequired=false)]
		public DateTime? StartedOn { get; set; }


		[DataMember(Name = "notifications", IsRequired=false)]
		public int? Notifications { get; set; }


		[DataMember(Name = "ref", IsRequired=false)]
		public Dictionary<string,object> Ref { get; set; }


	}
}

