using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public class ActivationStatus 
	{


		[DataMember(Name = "space_count", IsRequired=false)]
		public int? SpaceCount { get; set; }


	}
}

