using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public class Recurrence 
	{


		[DataMember(Name = "recurrence_id", IsRequired=false)]
		public int? RecurrenceId { get; set; }


		[DataMember(Name = "name", IsRequired=false)]
		public string Name { get; set; }


		[DataMember(Name = "config", IsRequired=false)]
		public Podio.API.Utils.SerializableDictionary Config { get; set; }


		[DataMember(Name = "step", IsRequired=false)]
		public int? Step { get; set; }


		[DataMember(Name = "until", IsRequired=false)]
		public string Until { get; set; }


	}
}

